services:
  cf-speedtest-hosts:
    image: ghcr.io/skylark36/cf-speedtest-hosts:latest
    container_name: cf-speedtest-hosts
    restart: always
    environment:
      - DOMAINS=example.com
      - GH_TOKEN=xxx
      - GIST_ID=xxx
      - CRON=0 0 * * *

