import os
import csv
import subprocess
import logging
from datetime import datetime
from typing import List

import httpx
from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.cron import CronTrigger
from dotenv import load_dotenv

# Load .env for local testing
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Config from Environment Variables
DOMAINS = os.getenv("DOMAINS", "").split(",")
GH_TOKEN = os.getenv("GH_TOKEN")
GIST_ID = os.getenv("GIST_ID")
GIST_FILENAME = os.getenv("GIST_FILENAME", "hosts.txt")
CRON_EXPR = os.getenv("CRON", "0 0 * * *")  # Default to daily at midnight
CF_ST_PATH = os.getenv("CF_ST_PATH", "./cfst")
CF_ST_ARGS = os.getenv("CF_ST_ARGS", "-dn 10 -p 0 -tl 300 -tll 5")

def run_speed_test() -> List[str]:
    """Runs CloudflareSpeedTest and returns the top IPs found."""
    logger.info("Starting Cloudflare Speed Test...")
    
    # Run the binary
    cmd = f"{CF_ST_PATH} {CF_ST_ARGS} -o result.csv"
    try:
        subprocess.run(cmd, shell=True, check=True)
    except subprocess.CalledProcessError:
        logger.error("CloudflareST failed.")
        return []

    # Parse result.csv
    ips = []
    if os.path.exists("result.csv"):
        with open("result.csv", mode='r', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader)  # Skip header
            for row in reader:
                if row:
                    ips.append(row[0])  # IP Address is the first column
    
    logger.info(f"Found IPs: {ips[:2]}")
    return ips[:2]

def generate_hosts(ips: List[str], domains: List[str]) -> str:
    """Generates hosts file content."""
    lines = [f"# Generated by Cloudflare Speed Test Gist Updater at {datetime.now().isoformat()}"]
    
    # Filter empty domains
    domains = [d.strip() for d in domains if d.strip()]
    
    if not ips:
        lines.append("# No IPs found in the last test.")
    else:
        for ip in ips:
            for domain in domains:
                lines.append(f"{ip} {domain}")
                
    return "\n".join(lines)

def update_gist(content: str):
    """Updates the GitHub Gist with the new hosts content."""
    if not GH_TOKEN or not GIST_ID:
        logger.warning("GH_TOKEN or GIST_ID not set. Skipping Gist upload.")
        logger.info(f"Generated hosts content:\n{content}")
        return

    logger.info(f"Updating Gist {GIST_ID}...")
    headers = {
        "Authorization": f"Bearer {GH_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    payload = {
        "files": {
            GIST_FILENAME: {
                "content": content
            }
        }
    }
    
    try:
        with httpx.Client() as client:
            response = client.patch(
                f"https://api.github.com/gists/{GIST_ID}",
                json=payload,
                headers=headers
            )
            if response.status_code == 200:
                print("✅ 成功! Gist 已更新。")
                print(f"🔗 链接: https://gist.github.com/{GIST_ID}")
            else:
                print(f"❌ 失败: 返回状态码 {response.status_code}")
                print(f"   响应内容: {response.text}")
    except httpx.HTTPError as e:
        logger.error(f"Failed to update Gist: {e}")

def job():
    """The main task to be executed."""
    ips = run_speed_test()
    if not ips:
        logger.warning("No IPs found, skipping update.")
        return
    # ips = ['104.18.238.182', '162.159.255.238']
    hosts_content = generate_hosts(ips, DOMAINS)
    update_gist(hosts_content)

if __name__ == "__main__":
    logger.info("Cloudflare Speed Test Tool Starting...")
    
    # Validation
    if not DOMAINS or not DOMAINS[0]:
        logger.error("DOMAINS environment variable is not set correctly.")
        exit(1)

    # 1. Run immediately upon startup (as requested by user)
    logger.info("Running initial check...")
    job()

    # 2. Schedule the cron job
    scheduler = BlockingScheduler()
    try:
        trigger = CronTrigger.from_crontab(CRON_EXPR)
        scheduler.add_job(job, trigger)
        logger.info(f"Job scheduled with cron: {CRON_EXPR}")
        scheduler.start()
    except Exception as e:
        logger.error(f"Failed to start scheduler: {e}")
        exit(1)
